INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (1, 'RoadRunner Records');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (2, 'Cactus Jack Records');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (3, 'Rostrum Records');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (4, 'Dreamville');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (5, 'Republic Records');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (6, 'Columbia Records');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (7, 'Syco Music');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (8, 'RCA Records');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (9, 'Warner Bros.');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (10, 'Warner Records');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (11, 'REMember Music');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (12, 'Sony Music Entertainment');
INSERT INTO blairs2_db.Label (label_id, label_name) VALUES (13, 'Epic Records');
