INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (1, 'Porcupine Tree', 1);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (2, 'Travis Scott', 2);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (3, 'Mac Miller', 3);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (4, 'J. Cole', 4);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (5, 'Post Malone', 5);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (6, 'Chance The Rapper', 8);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (7, 'Russ', 6);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (8, 'Childish Gambino', 8);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (9, 'Metro Boomin', 5);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (10, 'Camila Cabello', 7);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (11, 'Khalid', 8);
INSERT INTO blairs2_db.Artist (artist_id, artist_name, label_id) VALUES (12, 'Johnny Cash', 6);